config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'landings/index'

  resources :documents do
    member do
      get "vote"
    end
  end
  
  resources :company_stats

  get "/pages/*id" => 'pages#show', as: :page, format: false

  resources :categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
 
  resources :users, only: [:index, :show]
  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/views/elements/_doc_card.html.erb
<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
      <div class="mt-card-item">
          <div class="mt-card-avatar mt-overlay-1">
              <%= image_tag(doc.attachment.thumb_big.url) if doc.attachment? %>
              <div class="mt-overlay">
                  <ul class="mt-info">
                      <li>
                          <a class="btn blue" data-toggle="modal" href="#responsive<%= doc.id %>">
                              View
                          </a>
                      </li>
                      <li>
                          <a class="btn green" data-target="#stack<%= doc.id %>" data-toggle="modal"> Info </a>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="mt-card-content">
              <h3 class="mt-card-name"><%= doc.name %></h3>
          </div>
      </div>
  </div>
  <div id="responsive<%= doc.id %>" class="modal fade" tabindex="-1" data-width="760">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title"><%= doc.name %></h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div id="<%= no_spaces(doc.name) %><%= doc.id %>" class="col-md-6">
                
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <%= link_to "Download PowerPoint", doc.ppt_url, class:"btn btn-outline dark" if doc.ppt? %>
        <%= link_to "Download Word", doc.word_url, class:"btn btn-outline dark" if doc.word? %>
        <%= link_to "Download PDF", doc.attachment_url, class:"btn btn-outline dark" if doc.attachment? %>
        <button type="button" data-dismiss="modal" class="btn btn-outline dark">Close</button>
        <a class="btn green" data-target="#stack<%= doc.id %>" data-dismiss="modal" data-toggle="modal"> Info </a>
    </div>
  </div>
  <div id="stack<%= doc.id %>" class="modal fade" tabindex="-1" data-focus-on="input:first">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title"><%= doc.name %></h4>
      </div>
      <div class="modal-body">
        <div class="col-md-6">
          <h4>Description</h4>
          <p> <%= doc.desc %> </p>
        </div>
        <div class="col-md-6">
          <h4>Turnaround</h4>
          <p> The turnaround time for this project is:  </p>
          <h4>Tags</h4>
          <p><%= doc.tag_list %></p>
        </div>
        <div class="col-md-12">
          <p> If you would like to request a project like this one please contact your marketing coordinator or submit a request below and someone will be in conact with you shortly. </p>
        </div>
        <div class="form-group">
            <input class="form-control" type="text" data-tabindex="1" placeholder="Project Name"> 
        </div>
        <div class="form-group">
            <input class="form-control" type="text" data-tabindex="2" placeholder="Deadline"> 
        </div>
      </div>
      <div class="modal-footer">
          <button class="btn blue" data-toggle="modal" href="#stack2">Request</button>
          <button type="button" data-dismiss="modal" class="btn btn-outline dark">Close</button>
      </div>
  </div>
<script>PDFObject.embed("<%= doc.attachment.url %>", "#<%= no_spaces(doc.name) %><%= doc.id %>");</script>

app/views/elements/_footer.html.erb
<!-- BEGIN FOOTER -->
<p class="copyright"><%= Date.today.year %> © 
    <a href="http://Avisonyoung.com" title="Avison Young Website" target="_blank">Avison Young</a>
</p>
<a href="#index" class="go2top">
    <i class="icon-arrow-up"></i>
</a>
<!-- END FOOTER -->

app/views/elements/_navbar.html.erb
<!-- BEGIN HEADER -->
<header class="page-header">
    <nav class="navbar mega-menu" role="navigation">
        <div class="container-fluid">
            <div class="clearfix navbar-fixed-top">
                <!-- Brand and toggle get grouped for better mobile display -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="toggle-icon">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </span>
                </button>
                <!-- End Toggle Button -->
                <!-- BEGIN LOGO -->
                <%= link_to image_tag("AY_Reverse.png"), defined?(root_path) ? root_path : "#", class: "page-logo" %>
                <!-- END LOGO -->
                <!-- BEGIN SEARCH -->
                  <%= form_tag(documents_path, :method => "get", id: "search-form", class: "search") do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Search Documents", class: "form-control" %>
                  <% end %>
                <!-- END SEARCH -->
                <!-- BEGIN TOPBAR ACTIONS -->
                <div class="topbar-actions">
                    <!-- BEGIN USER PROFILE -->

                      <% if defined?(Devise) %>
                        <% if user_signed_in? %>
                          <div class="btn-group-img btn-group">
                            <button type="button" class="btn btn-sm md-skip dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <span>Account</span>
                            </button>
                            <ul class="dropdown-menu-v2" role="menu">
                                <li>
                                    <%= link_to "My Profile", edit_user_registration_path %>
                                </li>
                                <li>
                                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                                </li>
                            </ul>
                          </div>
                        <% else %>
                          <%= link_to "Login", new_user_session_path, class: "btn btn-solic blue" %>
                        <% end %>
                      <% end %>
                    <!-- END USER PROFILE -->
                </div>
                <!-- END TOPBAR ACTIONS -->
            </div>
            <!-- BEGIN HEADER MENU -->
            <div class="nav-collapse collapse navbar-collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown dropdown-fw <%= active_controller(['landings', 'pages', 'users', 'documents'], "active open selected") %>">
                        <a href="javascript:;" class="text-uppercase">
                            Dashboard </a>
                        <ul class="dropdown-menu dropdown-menu-fw">
                            <li class="<%= active_controller(['landings'], "active") %>">
                                <%= link_to "HOME", root_path %>
                            </li>
                            <!-- <li class="<%= active_for_id(['about'], "active") %>">
                                <%= link_to 'ABOUT', page_path('about') %>
                            </li> -->
                            <li class="<%= active_controller_action("users", ['index'], "active") %>">
                              <%= link_to "DIRECTORY", users_path %>
                            </li>
                            <li class="<%= active_controller_action("users", ['show'], "active") %><%= active_controller_action("documents", ['edit'], "active") %>">
                              <%= link_to "ADMIN", user_path(current_user) if current_user.role == "admin" %>
                            </li>
                        </ul>
                    </li>
                    <% @categories_collection.each do |cat| %>
                        <% if cat.is_root? %>
                            <li class="dropdown dropdown-fw  <%= active_nav(cat, "active open selected") %>">
                              <%= link_to cat.name, "#", class: "text-uppercase" %>
                              <% if cat.has_children? %>
                                <ul class="dropdown-menu dropdown-menu-fw">
                                    <% cat.children.each do |sub| %>
                                      <li class="dropdown <%= active_nav(sub, "active selected") %> <%= 'more-dropdown-sub' if sub.has_children? %>">
                                        <%= link_to sub.name.upcase, category_path(sub) %>
                                          <% if sub.has_children? %>
                                            <ul class="dropdown-menu">
                                              <% sub.children.each do |subsub| %>
                                                <li class="<%= active_nav(subsub, "active selected") %>" >
                                                  <%= link_to subsub.name, category_path(subsub) %>
                                                </li>
                                              <% end %>
                                            </ul>
                                        <% end %>
                                      </li>
                                    <% end %>
                                </ul>
                              <% end %>
                            </li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
            <!-- END HEADER MENU -->
        </div>
        <!--/container-->
    </nav>
</header>
            <!-- END HEADER -->