config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'landings/index'

  resources :documents do
    member do
      get "vote"
    end
  end
  
  resources :company_stats

  get "/pages/*id" => 'pages#show', as: :page, format: false

  resources :categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
 
  resources :users, only: [:index, :show]
  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
        :recoverable, :rememberable, :trackable, :validatable
  has_many :documents

  def admin?
    role == "admin"
  end

  def  regular?
    role == "regular"
  end

  def fullname
  	if self.first_name && self.last_name
      self.first_name + " " + self.last_name
    elsif self.first_name
      self.first_name
    else
      self.email
    end
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    flash[:info] = 'Registrations are not open'
    redirect_to new_user_session_path
  end

  def new
    flash[:info] = 'Registrations are not open'
    redirect_to new_user_session_path
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
  end
  
  def show
	@documents = Document.all
	@categories = Category.all
  end

end

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-bubble font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">Categories</span>
                </div>
                 <div class="actions">
                    <%= link_to new_category_path, class: "btn btn-default btn-sm"  do %>
                        <i class="fa fa-plus"></i> New
                    <% end %>
                </div>
            </div>
            <div class="portlet-body ">
                <div class="dd" id="nestable_list_1">
                    <ol class="dd-list">      
                        <%= nested_categories @categories_collection.arrange %>
                    </ol>
                </div>
            </div>
        </div>
    </div>
	<div class="col-md-6 pull-right">
		<div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-bubble font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">Documents</span>
                </div>
            	<div class="actions">
                    <%= link_to new_document_path, class: "btn btn-default btn-sm"  do %>
                        <i class="fa fa-plus"></i> New
                    <% end %>
                </div>
            </div>
			<table class="table table-striped">
			  <thead>
			    <tr>
			      <th>Name</th>
			      <th>Category</th>
			      <th>Last Updated</th>
			    </tr>
			  </thead>
			  <tbody>
			    <% @documents.each do |document| %>
			      <tr>
			        <td><%= link_to document.name, document_path(document) %></td>
			        <td><%= document.category.name if document.category %></td>
			        <td><%=l document.updated_at, format: :short %></td>
			        <td>
			        	<%= link_to document_path(document), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-sm btn-danger pull-right' do %>
			            	<i class="fa fa-trash"></i>
			          	<% end %>
			          	<%= link_to edit_document_path(document), :class => 'btn btn-sm blue pull-right' do %>
			          		<i class="fa fa-pencil"></i>
			          	<% end %>
			        </td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
	</div>
</div>