config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'landings/index'

  resources :documents do
    member do
      get "vote"
    end
  end
  
  resources :company_stats

  get "/pages/*id" => 'pages#show', as: :page, format: false

  resources :categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
 
  resources :users, only: [:index, :show]
  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/company_stat.rb
class CompanyStat < ActiveRecord::Base
  include PublicActivity::Common
end

app/controllers/company_stats_controller.rb
class CompanyStatsController < ApplicationController
  load_and_authorize_resource

  def index

  end

  def show
  end

  def new

  end

  def edit
  end

  def create
      respond_to do |format|
      if @company_stat.save
        @company_stat.create_activity :create, owner: current_user
        format.html { redirect_to @company_stat, notice: 'Stat was successfully created.' }
        format.json { render :show, status: :created, location: @company_stat }
      else
        format.html { render :new }
        format.json { render json: @company_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company_stat.update(company_stat_params)
        @company_stat.create_activity :update, owner: current_user
        format.html { redirect_to @company_stat, notice: 'Stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_stat }
      else
        format.html { render :edit }
        format.json { render json: @company_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company_stat.destroy
    @company_stat.create_activity :destroy, owner: current_user
    respond_to do |format|
      format.html { redirect_to company_stats_url, notice: 'Stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def company_stat_params
      params.require(:company_stat).permit(:name, :stat, :desc, :type)
    end
end

app/helpers/company_stats_helper.rb
module CompanyStatsHelper
end

app/views/company_stats/_form.html.erb
<%= form_for(@company_stat) do |f| %>
  <% if @company_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_stat.errors.count, "error") %> prohibited this company_stat from being saved:</h2>

      <ul>
      <% @company_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :stat %><br>
    <%= f.number_field :stat %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company_stats/edit.html.erb
<h1>Editing company_stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_stat %> |
<%= link_to 'Back', company_stats_path %>

app/views/company_stats/index.html.erb
<h1>Listing company_stats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stat</th>
      <th>Desc</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_stats.each do |company_stat| %>
      <tr>
        <td><%= company_stat.name %></td>
        <td><%= company_stat.stat %></td>
        <td><%= company_stat.desc %></td>
        <td><%= company_stat.type %></td>
        <td><%= link_to 'Show', company_stat %></td>
        <td><%= link_to 'Edit', edit_company_stat_path(company_stat) %></td>
        <td><%= link_to 'Destroy', company_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company stat', new_company_stat_path %>

app/views/company_stats/new.html.erb
<h1>New company_stat</h1>

<%= render 'form' %>

<%= link_to 'Back', company_stats_path %>

app/views/company_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_stat.name %>
</p>

<p>
  <strong>Stat:</strong>
  <%= @company_stat.stat %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @company_stat.desc %>
</p>

<p>
  <strong>Type:</strong>
  <%= @company_stat.type %>
</p>

<%= link_to 'Edit', edit_company_stat_path(@company_stat) %> |
<%= link_to 'Back', company_stats_path %>